# Generated by Django 4.2.7 on 2023-12-17 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assortment',
            name='brand',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='assortment',
            name='product',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='assortment',
            name='seasonality',
            field=models.CharField(max_length=250),
        ),
    ]
