# Generated by Django 4.2.7 on 2023-12-17 19:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_alter_assortment_brand_alter_assortment_product_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Geography',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=250)),
                ('federal_district', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rub', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.AlterModelOptions(
            name='assortment',
            options={'ordering': ['product']},
        ),
        migrations.AddField(
            model_name='assortment',
            name='manufacturer',
            field=models.CharField(default='Нет данных', max_length=250),
        ),
        migrations.AddIndex(
            model_name='assortment',
            index=models.Index(fields=['product'], name='sales_assor_product_24324f_idx'),
        ),
        migrations.AddField(
            model_name='sales',
            name='product_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sales.assortment'),
        ),
        migrations.AddField(
            model_name='sales',
            name='region_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sales.geography'),
        ),
    ]
