# Generated by Django 4.2.7 on 2023-12-17 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_geography_sales_alter_assortment_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sales',
            old_name='product_id',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='sales',
            old_name='region_id',
            new_name='region',
        ),
    ]
