# Generated by Django 4.2.7 on 2023-12-17 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_rename_product_id_sales_product_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assortment',
            name='seasonality',
        ),
    ]
