# Generated by Django 4.2.7 on 2023-12-17 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_remove_assortment_seasonality'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='unit',
            field=models.IntegerField(),
        ),
    ]
